[proxy]
mode = "cache"
host = "0.0.0.0"
port = "8000"
ssl_port = "8443"
remote_host = "https://lcs-cops.adobe.io"
ssl = true

[ssl]
cert_path = "proxy-cert.pfx"
cert_password = ""

[logging]
level = "info"
destination = "file"
file_path = "proxy-log.log"

[cache]
db_path = "proxy-cache.sqlite"
