[proxy]
host = "127.0.0.1:3030"
remote_host = "https://lcs-cops.adobe.io"
ssl = false

[logging]
console_log_level = "info"
log_to_file = false
file_log_level = "info"
file_log_path = "frl-proxy.log"

[cache]
enabled = true
cache_file_path = "frl-proxy.cache"
