[proxy]
mode = "cache"
host = "127.0.0.1:8443"
remote_host = "https://lcs-cops.adobe.io"
ssl = true

[ssl]
cert_path = "frl-proxy.pkcs"
cert_password = "for security, override with environment variable 'FRL_PROXY_SSL.CERT_PASSWORD'"

[logging]
level = "info"
destination = "console"
file_path = "frl-proxy.log"

[cache]
db_path = "frl-proxy.cache"
