[proxy]
# Settings to invoke proxy server
host = "127.0.0.1:8080"
remote_host = "https://lcs-cops.adobe.io"
ssl = false
# ssl_cert = "/path/to/ssl_cert.pem"
# ssl_key = "/path/to/ssl_key.pem"

[logging]
# Logging settings
console_log_level = "warn"
log_to_file = false
file_log_level = "info"
file_log_path = "frl-proxy.log"

[cache]
# Cache settings
enabled = true
cache_file_path = "frl-proxy.cache"
