[proxy]
mode = "cache"
host = "127.0.0.1"
port = "8080"
ssl_port = "8443"
remote_host = "https://lcs-cops.adobe.io"
ssl = true

[ssl]
use_pfx = false
pfx_path = "../certificates/pfx-testing.pfx"
cert_path = "../certificates/pfx-testing.cert"
key_path = "../certificates/pfx-testing.key"
password = "pfx-testing"

[logging]
level = "debug"
destination = "file"
file_path = "proxy-cert.log"
rotate_size_kb = 0
rotate_count = 10

[cache]
db_path = "proxy-cache.sqlite"

[network]
use_proxy = false
proxy_host = "127.0.0.1"
proxy_port = "8888"
use_basic_auth = false
proxy_username = ""
proxy_password = ""
