[proxy]
mode = "cache"
host = "127.0.0.1"
port = "8080"
ssl_port = "8443"
remote_host = "https://lcs-cops.adobe.io"
ssl = false

[ssl]
use_pfx = true
pfx_path = "proxy-certkey"
cert_path = "proxy-cert"
key_path = "proxy-key"
password = ""

[logging]
level = "off"
destination = "console"
file_path = "proxy-log.log"
rotate_size_kb = 0
rotate_count = 10

[cache]
db_path = "test-cache.sqlite"

[network]
use_proxy = false
proxy_host = "127.0.0.1"
proxy_port = "8888"
use_basic_auth = false
proxy_username = ""
proxy_password = ""
