[proxy]
db_path = "test-cache.sqlite"
mode = "connected"
host = "127.0.0.1"
port = "8080"
ssl_port = "8443"
ssl = false

[ssl]
use_pfx = true
pfx_path = "proxy-certkey"
cert_path = "proxy-cert"
key_path = "proxy-key"
password = ""

[logging]
level = "trace"
destination = "file"
file_path = "proxy-log.log"
rotate_size_kb = 0
rotate_count = 10

[upstream]
use_proxy = false
proxy_protocol = "http"
proxy_host = "127.0.0.1"
proxy_port = "8888"
use_basic_auth = false
proxy_username = ""
proxy_password = ""

[frl]
remote_host = "https://lcs-cops.adobe.io"

[log]
remote_host = "https://lcs-ulecs.adobe.io"
