[package]
name = "adlu-base"
authors = ["Daniel Brotsky <dev@clickonetwo.io>"]
version = "1.0.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
eyre = "0.6.7"
keyring = "1.1.2"
serde = "1.0.136"
serde_json = "1.0.79"
sha2 = "0.10.2"
