title: ADLU Documentation
description: Docs for the Adobe Desktop License Utilities from clickonetwo.io
theme: just-the-docs

url: https://clickonetwo.github.io/adobe-desktop-licensing-utilities

plugins:
  - jekyll-relative-links

mermaid:
  version: 10.3

aux_links:
  Latest Release: https://github.com/clickonetwo/adobe-desktop-licensing-utilities/releases/latest
