source 'https://rubygems.org'

gem "jekyll", "~> 4.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "~> 0.5.4"

# jekyll-relative-links turns .md links into .html links
# so the docs can be read directly on github as well as pages
gem "jekyll-relative-links", "~> 0.6.1"

# make it easy to check the integrity of the generated site
gem "html-proofer"
