name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore: ["docs"]
  pull_request:
    branches-ignore: ["docs"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-pc-windows-msvc]
        include:
          - arch: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - arch: x86_64-pc-windows-msvc
            os: windows-latest
          - arch: x86_64-apple-darwin
            os: macos-latest
          - arch: aarch64-apple-darwin
            os: macos-latest

    steps:
      - name: upgrade XCode
        uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          xcode-version: latest-stable

      - name: XCode build target to aarch64-apple-darwin
        run: |
          echo SDKROOT=$(xcrun --show-sdk-path) >> $GITHUB_ENV
          echo MACOSX_DEPLOYMENT_TARGET=$(xcrun --show-sdk-platform-version) >> $GITHUB_ENV
        if: ${{ matrix.arch == 'aarch64-apple-darwin' }}

      - name: fetch head
        uses: actions/checkout@v3

      - name: install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}
          components: rustfmt, clippy

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy check
        run: cargo clippy -- -D warnings

      - name: Test libraries (except when cross-compiling on mac)
        run: cargo test --target ${{ matrix.arch }} --workspace --lib -- --nocapture
        if: ${{ matrix.arch != 'aarch64-apple-darwin' }}

      - name: Build release adlu-proxy (all platforms)
        run: cargo build --target ${{ matrix.arch }} --package adlu-proxy  --release --locked

      - name: Build release adlu-decoder (mac and win only)
        run: cargo build --target ${{ matrix.arch }} --package adlu-decoder --release --locked
        if: ${{ matrix.arch != 'x86_64-unknown-linux-gnu' }}

      - name: Upload executables
        uses: actions/upload-artifact@v3
        with:
          name: executables
          path: |
            target/**/adlu-decoder
            target/**/adlu-decoder.exe
            target/**/adlu-proxy
            target/**/adlu-proxy.exe
