name: Publish executables

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x86_64-apple-darwin, aarch64-apple-darwin, x86_64-pc-windows-msvc]
        include:
          - arch: x86_64-pc-windows-msvc
            os: windows-latest
            executable_name: adlu-decoder.exe
            posted_name: adlu-decoder.windows_x86_64.exe
          - arch: x86_64-apple-darwin
            os: macos-latest
            executable_name: adlu-decoder
            posted_name: adlu-decoder.mac_x86_64
          - arch: aarch64-apple-darwin
            os: macos-latest
            executable_name: adlu-decoder
            posted_name: adlu-decoder.mac_arm64

    steps:
      - name: upgrade XCode
        uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          xcode-version: latest-stable

      - name: XCode build target to aarch64-apple-darwin
        run: |
          echo SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path) >> $GITHUB_ENV
          echo MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version) >> $GITHUB_ENV
        if: ${{ matrix.arch == 'aarch64-apple-darwin' }}

      - name: fetch head
        uses: actions/checkout@v2

      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.arch }}
          toolchain: stable

      - name: Build release locked
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:  --target ${{ matrix.arch }} --release --locked

      - name: Post release executable
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.arch }}/release/${{ matrix.executable_name }}
          asset_name: ${{ matrix.posted_name }}
          tag: ${{ github.ref }}
